name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@c84e59e194e019da3542a265aad72ab09482df63 # v8.1.20
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@c84e59e194e019da3542a265aad72ab09482df63 # v8.1.20
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@c84e59e194e019da3542a265aad72ab09482df63 # v8.1.20
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [22, 24]
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
  test:
    uses: vidavidorra/.github/.github/workflows/node-test.yml@c84e59e194e019da3542a265aad72ab09482df63 # v8.1.20
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [22, 24]
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
  code-coverage:
    uses: vidavidorra/.github/.github/workflows/node-test-coverage.yml@c84e59e194e019da3542a265aad72ab09482df63 # v8.1.20
    needs:
      - lint
      - build
      - test
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@c84e59e194e019da3542a265aad72ab09482df63 # v8.1.20
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
      - code-coverage
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
